### ISSUE TITLE
Error with 'superimpose' and associations : "Cannot convert value of type string to integer"

### ISSUE THREAD

**Issue by stonecooler** [dereuromark/cakephp-expose#8] opened 2020-03-20 15:45 UTC
Hello,

after I successfully converted a part of my application to this plugin
I tried the feature "superimpose" today and I got an error.

I want to store data (a customer with a "belongsTo" Association to an address)
this way:

```
$customer = $this->Customers->newEmptyEntity();
$formData = $this->request->getData();
$customer = $this->Customers->patchEntity($customer, $formData);
$customerSaved = $this->Customers->save($customer);
```

The error "Cannot convert value of type string to integer" at "\vendor\cakephp\cakephp\src\Database\Type\IntegerType.php"
 
The stacktrace item before is at "vendor\cakephp\cakephp\src\Database\Type\IntegerType.php" ($this->checkNumeric($value);)
and the argument is '3ba80978-8c2f-438c-9094-dee1d30e7704' ... a string.
That matched to the errormessage and the string looks like a UUID.

So where does the UUID came from?
I found it at the arguments of an other stracktrace item - the one where I call "Customers->save": 
```
object(App\Model\Entity\Customer) {
	'email' => 'paul@abdul.de',
	'gender' => (int) 1,
	'firstname' => 'Paula',
	'lastname' => 'Abdul',
	'address' => object(App\Model\Entity\Address) {

		'organization' => 'Dönerbude',
		'addressline1' => 'Bahnhofstrasse 54',
		'addressline2' => '',
		'addressline3' => '',
		'city' => 'Kiel',
		'zip' => '23456',
		'area' => 'Schleswig Holstein',
		'nation' => 'DE',
		'uuid' => '3ba80978-8c2f-438c-9094-dee1d30e7704',
		'id' => '3ba80978-8c2f-438c-9094-dee1d30e7704',
		'_id' => (int) 39,
		'[new]' => false,
		'[accessible]' => [
			[maximum depth reached]
		],
		'[dirty]' => [[maximum depth reached]],
		'[original]' => [[maximum depth reached]],
		'[virtual]' => [[maximum depth reached]],
		'[hasErrors]' => false,
		'[errors]' => [[maximum depth reached]],
		'[invalid]' => [[maximum depth reached]],
		'[repository]' => 'Addresses'
	
	},
	'created' => object(Cake\I18n\FrozenTime) {

		'time' => '2020-03-20 15:02:19.670336+00:00',
		'timezone' => 'UTC',
		'fixedNowTime' => false
	
	},
	'modified' => object(Cake\I18n\FrozenTime) {

		'time' => '2020-03-20 15:02:19.670378+00:00',
		'timezone' => 'UTC',
		'fixedNowTime' => false
	
	},
	'uuid' => '0bd32667-3317-4e5d-9a24-ebeafa8210f5',
	'password' => '$2y$10$VwIDuh8V475CXNcagbjnAOkW1iFRJVc11HdXlA7ke9hRwUCNXC/QO',
	'address_id' => '3ba80978-8c2f-438c-9094-dee1d30e7704',
	'[new]' => true,
	'[accessible]' => [
		'id' => false,
		'address' => true,
		'email' => true,
		'password_input' => true,
		'password_current' => true,
		'password_repeat' => true,
		'gender' => true,
		'firstname' => true,
		'lastname' => true,
		'role' => true,
		'lastlogin' => false,
		'created' => false,
		'modified' => false
	],
	'[dirty]' => [
		'email' => true,
		'gender' => true,
		'firstname' => true,
		'lastname' => true,
		'address' => true,
		'created' => true,
		'modified' => true,
		'uuid' => true,
		'password' => true,
		'address_id' => true
	],
	'[original]' => [],
	'[virtual]' => [],
	'[hasErrors]' => false,
	'[errors]' => [],
	'[invalid]' => [],
	'[repository]' => 'Customers'
}

```
I guess the "'address_id' => '3ba80978-8c2f-438c-9094-dee1d30e7704',"
causes the problem, because the field 'address_id' is not a string in the database (it is an integer).

An Issues? Or do I use the plugin incorrectly? Do I have to disable "autoFinder" and write my own find-method for that?

**Comment by dereuromark** [comment] 2020-03-20 16:24
I think you might not have read the part about this being only allowed to be enabled per dynamic use case, never globally.
Only do that in the controllers that need public exposed UUIDs, otherwise this is not needed to be loaded as behavior on the table(s).

https://github.com/dereuromark/cakephp-expose/tree/master/docs#superimposition

As such this can also only be used on primary level to lookup - it can however be used on multiple levels to display.
If you need to modify entities we will have to check how we can allow this to work. Not sure yet.

**Comment by dereuromark** [comment] 2020-03-20 16:56
If you have ideas how to allow editing related records, please share this, or make a PR.
I imagine it has to be similar as [this](https://github.com/UseMuffin/Obfuscate) solved it.

**Comment by stonecooler** [comment] 2020-03-20 18:11
Okay, I moved `addBehavior` from my `AppTable` to the `CustomerTable` - so the `AddressTable` does not have the expose behavior ("never globally"). The component for "superimposition" is loaded in the controller. No problems with the address association now, and okay for my usecase. But if my AddressTabel needs in an other usecase public exposed UUID's? So I was trying to load the behavior for the table dynamic in the controller:
```
$this->Customers->addBehavior('Expose.Expose', ['on' => 'beforeSave']);
```
This works. But I don't know if this is okay. Nothing found about loading behaviors dynamic in the controller. So solved for me. Thank you

**Comment by dereuromark** [comment] 2020-03-20 18:14
Sry, my advice was only for Superimpose
Expose can be on any as this one does not affect the primary key superimposition and thus does not interfere with any read or save operation.

**Comment by dereuromark** [comment] 2020-03-20 18:20
Best to check the linked docs I gave you as there should be no need to manually add the behavior, when the component is used.

**Comment by stonecooler** [comment] 2020-03-20 18:26
I loaded the Superimpose component in the controller (initialize) with the config for only the action where it is needed. And the Model behavior was added in AppTable. That was original setup as descriped in the docs.

**Comment by dereuromark** [comment] 2020-03-20 18:29
I see. The problem is then that it gets passed also to the addresses and that is what is causing this.
Feel free to make suggested improvements to docs or code once it is all working as you need it.

**Comment by dereuromark** [comment] 2020-03-20 18:58
Should be fixed with https://github.com/dereuromark/cakephp-expose/commit/4e00093850d93492f6ad1ab576492da07bfbda85

**Comment by dereuromark** [comment] 2020-03-21 01:04
So basic CRUD is now possible.
More complex saving operations that include foreign_key setting from a just created entity seems not be possible right now using Superimpose.
You can now set `recursive` to false here and you can still save those entities.

**Closed as completed** 2020-03-21 14:53 UTC
